title: Portfolio
author: William Donovan
email: donovanree@comcast.net
description: > # this means to ignore newlines until "baseurl:"
 Here is my awesome portfolio.

# social links
twitter_username: bdonovan002@outlook.com
github_username:  bdonovan2

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
